site_name: Develop Notes

theme: 
  name: cyborg

nav:
  - Home: index.md
  - Computer Vision:
    - Overview: vision/index.md
    - Filter: vision/filter.md
  - .NET Development:
    - Overview: dotnet/index.md