site_name: Develop Notes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme: 
  name: material

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          name: 简体中文
        - locale: en
          default: true
          name: English

nav:
  - Home: index.md
  - Computer Vision:
    - Overview: vision/index.md
    - Filter: vision/filter.md
  - .NET Development:
    - Overview: dotnet/index.md